### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by gotnull** [allenai/lm-explorer#12]
python app.py --port 8000 --dev

```
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    import torch
  File "/Users/fulvio/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/Users/fulvio/anaconda3/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/fulvio/anaconda3/lib/python3.7/site-packages/torch/lib/libshm.dylib
  Reason: image not found
```

**Comment by jqueguiner** [comment]
on mac : 
```bash
brew install llvm
brew install libomp
```
